### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by jonas-w**
## Before this PR

Our foundry-dev-tools conda-forge feedstock is failing, because of the version specifier mismatch between the conda-forge recipe and the palantir-oauth-client package.
https://github.com/conda-forge/foundry-dev-tools-feedstock/pull/22

Your [feedstock recipe specifies `requests-oauthlib>=1.3.1`](https://github.com/conda-forge/palantir-oauth-client-feedstock/blob/c07429eaf9f71ca3a0bbd14557beb30fd244b58c/recipe/meta.yaml#L27) while your `pyproject.toml` specified `requests-oauthlib="^1.3.1"` which equals `requests-oauthlib<2.0.0,>=1.3.1`.

## After this PR

Theoretically fixing the conda-forge recipe by locking the request-oauthlib library to `<2` would be enough, but I wondered if the version locking is needed.
So I loosened the restrictions on the dependencies for this project, and the only version change that happened was `black` updated to 24, and `requests-oauthlib` to 2.0.0, everything else remained at the same version.

Commits:
- **chore: bump black version and reformat**
- **chore: bump requests-oauthlib version to 2.0.0**

## Possible downsides?

None that I'm aware of, the release notes for `requests-oauthlib` show some bug fixes, and that it now also supports python version from 3.8 to 3.12.
https://github.com/requests/requests-oauthlib/blob/master/HISTORY.rst

## Are Docs needed?

No

### CODE REVIEW

**Comment by jonas-w** [comment]
I still can't use the `changelog-app` so I added one manually again.

**Review by talDias — APPROVED** [review]

**Review by talDias — COMMENTED** [review]
:+1:

**Comment by nicornk** [comment]
@talDias Can you kick-off a release after merging this PR?

**Review by tom-s-powell — APPROVED** [review]

**Comment by tom-s-powell** [comment]
@jonas-w appreciate the PR. Would it be possible to merge in the latest develop?

**Pull request merged**
